### ISSUE TITLE
Slow on Windows?

### ISSUE THREAD

**Issue by AeliusSaionji** [gpanders/vim-oldfiles#6] opened 2021-08-15 12:53 UTC
Hello!
When pulling up the full list, no filter, it takes 2-3 seconds to load. Any idea why that might be?

Thanks!

**Comment by gpanders** [comment] 2021-08-15 15:35
I'm not sure why. Can you try it with all other plugins disabled and see if it still occurs? What does `:set viminfo?` show? If you run the builtin command `:oldfiles` (lowercase `o`) is it also slow?

**Comment by AeliusSaionji** [comment] 2021-08-17 17:40
Just sat down at my desktop and can't replicate the issue there. The problem is only on my laptop and the builtin :oldfiles does run slow on my laptop, too. But I can't tell if it's slow to load, or if it's _scrolling_ slow, like the terminals sometimes do.

Maybe my oldfiles history on my laptop is much bigger or has problem contents. I'll get back to you with the output of viminfo shortly.

**Comment by AeliusSaionji** [comment] 2021-08-24 07:01
Sorry for the image, can't figure out how to copy this.
![image](https://user-images.githubusercontent.com/4342746/130571367-b2a2b189-7fee-4e14-a592-b390466c866c.png)

Interestingly, the buildin :oldfiles is NOT slow in the terminal, only in gvim.
However, :Oldfiles is slow for both.

**Comment by gpanders** [comment] 2021-08-24 11:39
As I'm unable to reproduce this, I'll have to ask you to be my guinea pig and try some things out for me :)

> Can you try it with all other plugins disabled and see if it still occurs?

Firstly, did you do this? I want to be sure this isn't being caused by another plugin before we go too far down any rabbit holes.

Secondly, open up the `autoload/oldfiles.vim` file in your installed version of the plugin and change line 42 from

```vim
  let cmd = 'filter' . (a:bang ? '! ' : ' ') . pat . ' oldfiles'
```

to simply

```vim
  let cmd = 'oldfiles'
```

And let me know if that changes anything.

**Comment by AeliusSaionji** [comment] 2021-08-24 20:24
I tried disabling other plugins and changed that line: no difference.

Did some searching, and 
`syntax sync minlines=256` as suggested by https://eduncan911.com/software/fix-slow-scrolling-in-vim-and-neovim.html does considerably speed up `:Oldfiles`.

What do you think this means? I have no idea how or why this would be.

**Comment by gpanders** [comment] 2021-08-24 20:48
I am honestly not sure. I don't know why the quickfix list would be slow if everything else is not.

Do you notice if the quickfix list is slow when using it with things besides Oldfiles?

In any case, it sounds like you can solve this by adding this to your `.vimrc`:

```vim
autocmd BufWinEnter * if &buftype ==# 'quickfix' | syntax sync minlines=10 | endif
```

You can play around with the value of `minlines`.

**Comment by AeliusSaionji** [comment] 2021-08-24 21:01
I'm sorry I gave you bad info.
Right now it seems like the first load is slow, and subsequent loads are usually fast. My testing with these syntax settings were just me not realizing this for some reason.

I could have sworn it was behaving differently... this initial slow, subsequently fast is also happening on my desktop.

**Comment by gpanders** [comment] 2021-08-24 22:33
> Right now it seems like the first load is slow, and subsequent loads are usually fast.

This strongly implies that the issue is not with this plugin. Oldfiles isn't doing any kind of caching so there's no reason it would be faster on subsequent invocations.

I'm going to close this as I don't believe the slowness is caused by Oldfiles itself. If you find some evidence to the contrary I'll re-open the issue, but seeing as I'm unable to reproduce it I don't have much hope that I'll be much help.

**Closed as completed by gpanders** 2021-08-24 22:33 UTC

**Comment by AeliusSaionji** [comment] 2021-08-24 22:43
OK, thank you for the help thus far!
